# Generated by Django 3.0.4 on 2020-03-28 15:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=13, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('verfication_completed', models.BooleanField(default=False)),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'volunteer_detail',
                'ordering': ['-verfication_completed'],
            },
        ),
    ]
