# Generated by Django 3.0.4 on 2020-03-29 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='volunteerdetails',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='volunteerdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteerdetails',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerdetails',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
