# Generated by Django 3.0.4 on 2020-03-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
