# Generated by Django 3.0.4 on 2020-04-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_customerprofiledata_volunteerprofiledata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerprofiledata',
            table='customer_profile_table',
        ),
        migrations.AlterModelTable(
            name='volunteer',
            table='volunteer_detail',
        ),
        migrations.AlterModelTable(
            name='volunteerprofiledata',
            table='volunteer_profile_table',
        ),
    ]
