# Generated by Django 3.0.4 on 2020-03-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200328_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='other_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='order_status',
            field=models.CharField(choices=[('N', 'Not Verified'), ('V', 'Verified'), ('T', 'Taken'), ('I', 'InTransit'), ('D', 'Deliveried'), ('U', 'unreachable')], default='N', max_length=2),
        ),
    ]
