# Generated by Django 3.0.4 on 2020-03-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200328_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'ordering': ['-verfication_completed']},
        ),
        migrations.RenameField(
            model_name='customerdetails',
            old_name='details_verification',
            new_name='verfication_completed',
        ),
    ]
